### ISSUE TITLE
Compatibility with Trails to Azure 1.1.18

### ISSUE THREAD

**Issue by nibau** [shinkiseki/MorePortraitsInAzure#10]
Thank you for this mod!

Just wanted to let you know that they've released a new update 1.1.18 yesterday (there is also one for Trails from Zero).
https://store.steampowered.com/news/app/1668520/view/3664295044557522358

It probably has an impact on this mod as many scena files have been modified according to steamdb:
https://steamdb.info/patchnotes/12033403/

**Comment by Kyuuhachi** [comment]
In Zero, the only change in the scenas was to add color to the schedule in the guild, in c1010 and c101c. In the Japanese scripts, they also changed `『セピス換金』を選んだ後` to `『換金をする』を選んだ後` in c1310, which is something with IBC I think.

Azure had significantly more changes. I think this list is exhaustive, but it's probably best if you double-check:
- the aforementioned schedule color
- most four-digit voiceline attributes (`#....V`) were removed (but not all)
- added commas in the "but you left it there" on every chest
- catspeak now uses `〜` instead of `-`, in 
- change `!?` to `?!` in c0000, c1410, e0410, e3600, m0101, r2030, t0510, t1380
- translation changes in c0100_1, t1530, t1550, t4010
- capitalization fixes in c0140, c014b, c1100
- typos in in c0150, c1110, r1080, t0000, t0500 (×2)
- fix incorrect formatting in c110d and e0410
- change a face in c1110
- change speaker in c1120
- rename "Republican Soldier" to "Royal Guardsman" in c1540
- small formatting fix in debug script b0100

Japanese has:
- schedule color
- four-digit voicelines
- the IBC thing
- change `『△ボタン＋Ｌ１ボタン』` to `『#165I＋#167I』` in c1430
- formatting in e0410
- change `Crossbell Police School` to `Crossbell Police Academy` in r1030
- typo in c0110, r1530, t1310, t6010

**Comment by shinkiseki** [comment]
Thanks for the heads up! The mod should work properly while installed on top of the v1.1.18 patch -- it'll just overwrite the updates made in the patch. I'm working on a mod update already, which should come out in the coming days for both JP and EN.

**Comment by shinkiseki** [comment]
v1.1.18 support is now live with the v1.2.0 mod!
